# Generated by Django 3.2.7 on 2021-09-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
