# Generated by Django 3.2.7 on 2021-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание:'),
        ),
    ]
