# Generated by Django 3.2.7 on 2021-09-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='product',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='storage',
        ),
        migrations.AddField(
            model_name='phone',
            name='accum_volume',
            field=models.CharField(default=1, max_length=255, verbose_name='Объем батареи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='diagonal',
            field=models.CharField(default=1, max_length=255, verbose_name='Диагональ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='display_type',
            field=models.CharField(default=12, max_length=255, verbose_name='Тип дисплея'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='frontal_cam_mp',
            field=models.CharField(default=1, max_length=255, verbose_name='Фронтальная камера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='main_cam_mp',
            field=models.CharField(default=12, max_length=255, verbose_name='Главная камера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.CharField(default=1, max_length=255, verbose_name='Оперативная память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='resolution',
            field=models.CharField(default=1, max_length=255, verbose_name='Разрешение экрана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AddField(
            model_name='phone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем встраивамой памяти'),
        ),
    ]
